const baseColors = {
  transparent: 'var(--transparent)',
  black: 'var(--black)',
  white: 'var(--white)',
  gray: [
    'var(--gray-50)',
    'var(--gray-100)',
    'var(--gray-200)',
    'var(--gray-300)',
    'var(--gray-400)',
    'var(--gray-500)',
    'var(--gray-600)',
    'var(--gray-700)',
    'var(--gray-800)',
    'var(--gray-900)',
  ],
  blue: [
    'var(--blue-50)',
    'var(--blue-100)',
    'var(--blue-200)',
    'var(--blue-300)',
    'var(--blue-400)',
    'var(--blue-500)',
    'var(--blue-600)',
    'var(--blue-700)',
    'var(--blue-800)',
    'var(--blue-900)',
  ],
  yellow: [
    'var(--yellow-50)',
    'var(--yellow-100)',
    'var(--yellow-200)',
    'var(--yellow-300)',
    'var(--yellow-400)',
    'var(--yellow-500)',
    'var(--yellow-600)',
    'var(--yellow-700)',
    'var(--yellow-800)',
    'var(--yellow-900)',
  ],
  pink: [
    'var(--pink-50)',
    'var(--pink-100)',
    'var(--pink-200)',
    'var(--pink-300)',
    'var(--pink-400)',
    'var(--pink-500)',
    'var(--pink-600)',
    'var(--pink-700)',
    'var(--pink-800)',
    'var(--pink-900)',
  ],
  red: [
    'var(--red-50)',
    'var(--red-100)',
    'var(--red-200)',
    'var(--red-300)',
    'var(--red-400)',
    'var(--red-500)',
    'var(--red-600)',
    'var(--red-700)',
    'var(--red-800)',
    'var(--red-900)',
  ],
};

const defaultColors = {
  // theme specification colors
  text: 'var(--colors-text)',
  background: 'var(--colors-background)',
  primary: 'var(--colors-primary)',
  secondary: 'var(--colors-secondary)',
  accent: 'var(--colors-accent)',
  highlight: 'var(--colors-highlight)',
  muted: 'var(--colors-muted)',
  // additional colors
  overlay: 'var(--colors-overlay)',
  textMuted: 'var(--colors-text-muted)',
  primaryHover: 'var(--colors-primary-hover)',
  success: 'var(--colors-success)',
  info: 'var(--colors-info)',
  warning: 'var(--colors-warning)',
  danger: 'var(--colors-danger)',
};

export const colors = {
  ...baseColors,
  ...defaultColors,
};
