const commonButtonStyles = {
  py: 2,
  px: 3,
  cursor: 'pointer',
  fontSize: '100%',
  lineHeight: 'inherit',
};

export const buttons = {
  simple: {
    ...commonButtonStyles,
    backgroundColor: 'primary',
    border: 'none',
    color: 'white',
    fontWeight: 'bold',
    borderRadius: 'default',
    '&:hover': {
      backgroundColor: 'primaryHover',
    },
  },
  pill: {
    ...commonButtonStyles,
    backgroundColor: 'primary',
    border: 'none',
    color: 'white',
    fontWeight: 'bold',
    borderRadius: 'full',
    '&:hover': {
      backgroundColor: 'primaryHover',
    },
  },
  outline: {
    ...commonButtonStyles,
    backgroundColor: 'transparent',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'primary',
    color: 'primary',
    fontWeight: 'semibold',
    borderRadius: 'default',
    '&:hover': {
      backgroundColor: 'primary',
      color: 'white',
      borderColor: 'transparent',
    },
  },
  bordered: {
    ...commonButtonStyles,
    backgroundColor: 'primary',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'primaryHover',
    color: 'white',
    fontWeight: 'bold',
    borderRadius: 'default',
    '&:hover': {
      backgroundColor: 'primaryHover',
    },
  },
  disabled: {
    ...commonButtonStyles,
    backgroundColor: 'primary',
    border: 'none',
    opacity: 0.5,
    cursor: 'not-allowed',
    color: 'white',
    fontWeight: 'bold',
    borderRadius: 'default',
  },
  '3D': {
    ...commonButtonStyles,
    backgroundColor: 'primary',
    border: 'none',
    borderBottomWidth: '4px',
    borderBottomStyle: 'solid',
    borderBottomColor: 'primaryHover',
    color: 'white',
    fontWeight: 'bold',
    borderRadius: 'default',
    transition: 'transform 0.3s ease-in-out',
    '&:hover': {
      transform: 'translateY(-1px)',
    },
  },
  elevated: {
    ...commonButtonStyles,
    backgroundColor: 'white',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'gray.4',
    color: 'text',
    fontWeight: 'bold',
    borderRadius: 'default',
    boxShadow: 'default',
    '&:hover': {
      backgroundColor: 'gray.1',
    },
  },
};
