const baseColors = {
  transparent: 'transparent',
  black: '#000',
  white: '#fff',
  gray: [
    'var(--gray-50)',
    'var(--gray-100)',
    'var(--gray-200)',
    'var(--gray-300)',
    'var(--gray-400)',
    'var(--gray-500)',
    'var(--gray-600)',
    'var(--gray-700)',
    'var(--gray-800)',
    'var(--gray-900)',
  ],
  teal: [
    'var(--teal-50)',
    'var(--teal-100)',
    'var(--teal-200)',
    'var(--teal-300)',
    'var(--teal-400)',
    'var(--teal-500)',
    'var(--teal-600)',
    'var(--teal-700)',
    'var(--teal-800)',
    'var(--teal-900)',
  ],
  yellow: [
    'var(--yellow-50)',
    'var(--yellow-100)',
    'var(--yellow-200)',
    'var(--yellow-300)',
    'var(--yellow-400)',
    'var(--yellow-500)',
    'var(--yellow-600)',
    'var(--yellow-700)',
    'var(--yellow-800)',
    'var(--yellow-900)',
  ],
  olive: [
    'var(--olive-50)',
    'var(--olive-100)',
    'var(--olive-200)',
    'var(--olive-300)',
    'var(--olive-400)',
    'var(--olive-500)',
    'var(--olive-600)',
    'var(--olive-700)',
    'var(--olive-800)',
    'var(--olive-900)',
  ],
  orange: [
    'var(--orange-50)',
    'var(--orange-100)',
    'var(--orange-200)',
    'var(--orange-300)',
    'var(--orange-400)',
    'var(--orange-500)',
    'var(--orange-600)',
    'var(--orange-700)',
    'var(--orange-800)',
    'var(--orange-900)',
  ],
};

const defaultColors = {
  // theme specification colors
  text: 'var(--colors-text)',
  background: 'var(--colors-background)',
  primary: 'var(--colors-primary)',
  secondary: 'var(--colors-secondary)',
  accent: 'var(--colors-accent)',
  highlight: 'var(--colors-highlight)',
  muted: 'var(--colors-muted)',
  // additional colors
  textMuted: 'var(--colors-text-muted)',
  primaryHover: 'var(--colors-primary-hover)',
  success: 'var(--colors-success)',
  info: 'var(--colors-info)',
  warning: 'var(--colors-warning)',
  danger: 'var(--colors-danger)',
};

export const colors = {
  ...baseColors,
  ...defaultColors,
};
